# Generated by Django 5.2.13 on 2026-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
