# Generated by Django 6.0.4 on 2026-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userprofile_verified_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('applicant', 'Abituriyent'), ('student', 'Talaba'), ('professional', 'Mutaxassis')], default='student', max_length=20),
        ),
    ]
