# Generated by Django 5.2.13 on 2026-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userprofile_role_selected_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
