# Generated by Django 6.0.4 on 2026-04-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_userprofile_skills_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
