# Generated by Django 6.0.4 on 2026-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_subject_educationalresource_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
