# Generated by Django 6.0.4 on 2026-04-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_userprofile_selected_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major_subject_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major_subject_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mandatory_subjects_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
