# Generated by Django 6.0.4 on 2026-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_course_university_lmsunit_lmstest_subjectcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_plan_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
