# Generated by Django 6.0.4 on 2026-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_userprofile_daily_plan_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_tasks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='energy_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='knowledge_precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='task_backlog_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_plan_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
